### ISSUE TITLE
Lowercase chars do not work as action_keys or subgrid_action_keys

### ISSUE THREAD

**Issue by whollacsek** [croian/mouseless-issues#10]
### mouseless version

0.2

### macOS version

15

### What happened?

After changing the available keys and the grid rows and columns the app stopped working. Pressing the keys doesn't move the green dot however pressing space still validate as a click thus hiding the overlay grid.

### Steps to Reproduce

Change the keys in config screen and the amount of rows and columns

**Comment by whollacsek** [comment]
The 3 rows on the keyboard, q to p, a to ; and z to .

Then I set the grid count to 10 and 3.

**Comment by croian** [comment]
I'm guessing you used lowercase letters? :) I should definitely support them, will fix.  I'll also make it so spaces are ignored, so you can visually separate blocks of letters.

**Comment by whollacsek** [comment]
Ah yes I used lowercase

**Comment by croian** [comment]
fixed! and whitespace in the config strings is ignored, so you can separate them for clarity.

**note** that this doesn't (yet) mean you can use both lowercase and uppercase versions of the same key in the action string (only the first will be 'clickable').  **aside:** I tried this out and while it is possible and pretty powerful (along with all the shifted/unshifted symbol characters it makes for a pretty fine grid with no subgrid (!)), I need to optimize performance and usability.

**Comment by whollacsek** [comment]
Thanks I'll test it when I have some time

**Comment by croian** [comment]
released in v0.2.1 👍
