### ISSUE TITLE
Mouse actions - basic click without selecting field is not clicking on current cursor position

### ISSUE THREAD

**Issue by ronnyworm** [croian/mouseless-issues#100]
### mouseless version

v0.2.1

### macOS version

14.7.2

### What happened?

https://github.com/croian/mouseless-issues/blob/main/mouseless_documentation.md
"you can also press space before entering any characters, or after entering one, to click where the cursor is"
-> no this clicks in the center for me

I'm using two monitors but it also occurs each time when just using it with the Mac display.

### Steps to Reproduce

- Open overlay
- press space

expectation: click where cursor is
behaviour: clicks in center of the screen

**Comment by ognistik** [comment]
My guess is that the docs meant to say "to click where the green dot is" ... [here's a related thread](https://github.com/croian/mouseless-issues/issues/89)

**Comment by ronnyworm** [comment]
Oh right, not a bug then. I'm closing this and look forward to https://github.com/croian/mouseless-issues/issues/89#issuecomment-2559951460
