### ISSUE TITLE
Russian layout is not working in overlay

### ISSUE THREAD

**Issue by Tauka** [croian/mouseless-issues#104]
### mouseless version

0.2.2

### macOS version

14.6.1

### What happened?

Hi,

I saw that in v0.2.2 support for non-english keyboards was added, but it is still not working for me for Russian keyboard. Overlay doesn't respond to keys when I switch to russian.

### Steps to Reproduce

- Switch to russian keyboard
- Activate overlay
- Try to press any key

**Comment by croian** [comment]
Hi @Tauka, are you using Russian characters in the overlay (i.e. the mouse_action_keys and subgrid_mouse_action_keys in the config editor)?  Currently, overlay cells are matched by the character, not the physical keycode/location, but I aim to change this soon, so that you can select a cell no matter which keyboard layout you have active.

**Comment by Tauka** [comment]
I see, I misunderstood the way it works with non-english layout, I was expecting location based as you described. I mostly use english layout, sometimes I need to switch to russian, I reckon currently there is no way to specify mouse_action_keys on per language basis?

**Comment by croian** [comment]
@Tauka do you mean like automatically switching the mouse_action_keys based on which layout is active?  there's currently not a way to do that (nor a quick way to do it manually), but it's an interesting idea.  is that something you think you would use?  or would you prefer just defining the action_keys in one language/alphabet, and using it across both layouts?

**Comment by Tauka** [comment]
I meant something like this in config:

```
en_US:
  mouse_action_keys: ...
ru_RU:
 mouse_action_keys: ...
 ```
 
But I would much rather prefer single action_keys working across different layouts, so that even when I switch to russian layout, I can still use mouseless as if I was in english layout. I think I saw it mentioned in other issue/discussion? Feel free to close this one, since it's already addressed

By the way still loving the app and I'm glad to see how it's actively improving, I use it everyday, and aim to fully replace my mouse interactions with it (there are still some cases where I have to fallback to using mouse, but I hope in the future it will be possible 🙂)

**Comment by croian** [comment]
Ah, I see what you mean.

Yeah, there was some discussion around this problem and potential solutions in #79.  I've made a dedicated issue for it now, #108.

> By the way still loving the app and I'm glad to see how it's actively improving, I use it everyday...

Love to hear it, thank you!  :)
