### ISSUE TITLE
Typo in the label during onboarding popup

### ISSUE THREAD

**Issue by rudavko** [croian/mouseless-issues#12]
### mouseless version

v0.2.0

### macOS version

15.2 (24C98)

### What happened?

Mouseless needs the 'accessibility' permission to perform its primary function (**excuting** mouse events via keypresses).

### Steps to Reproduce

launch for the first time

**Comment by croian** [comment]
Will fix, thank you! :)

**Comment by croian** [comment]
released in v0.2.1

did a full sweep over the non-lib part of the codebase, but then may have introduced some more :) need to come up with a good workflow for this, as i don't like having spellchecker on all the time 😮‍💨
