### ISSUE TITLE
QWERTZ Support (And other keyboard types)

### ISSUE THREAD

**Issue by Fadope1** [croian/mouseless-issues#29]
### mouseless version

0.2.0

### macOS version

Sequoia 15.1

### What happened?

If overlay is active I can see for example "Z B" then I press "Z B" on my keyboard but it will select "Y B". So to fix this I always need to press y instead of z and the other way around.

### Steps to Reproduce

1. Have QWERTZ layout keyboard
2. Activate layout
3. Try to go into a cell with Y in it

**Comment by croian** [comment]
hi @Fadope1, please try out v0.2.1 (https://mouseless.click#download -- do a hard refresh if you see 0.2.0 from that) and let me know if its fixed, thanks!

**Comment by croian** [comment]
if you find that it *mostly* works in v0.2.1, but *some* keys don't, we can close this issue and roll the convo into #30 

but hopefully it fully works :)

**Comment by croian** [comment]
going to close this, @Fadope1, but if you try v0.2.1 and you find there are any worse/different issues than #30, please re-open!
