### ISSUE TITLE
Homebrew cask

### ISSUE THREAD

**Issue by drod3763** [croian/mouseless-issues#3]
### Problem Description

Be nice to be able to install this via Homebrew cask.

### Proposed Solution

Create a cask with the following instructions:
https://docs.brew.sh/Adding-Software-to-Homebrew#writing-the-cask

**Comment by croian** [comment]
Interesting, I can definitely see the value in that.  Thank you for the suggestion; will keep it in mind!

**Comment by croian** [comment]
thanks to @unitof, this is done! 🎉 https://github.com/Homebrew/homebrew-cask/pull/195324
