### ISSUE TITLE
"Escape" Shortcut still triggers in the app below

### ISSUE THREAD

**Issue by ognistik** [croian/mouseless-issues#35]
### mouseless version

mouseless v0.2.1

### macOS version

15.2 (24C101)

### Other system input apps

Karabiner Elements

### What happened?

My key to hide the overlay is "Escape", and it works well. But sometimes I make typing mistakes, and since there's currently no way to undo them. I have to hide the overlay by pressing escape to try again. The problem is when I have a dialog box open or I'm using an app that also uses escape. I expect the escape key to only work for Mouseless and not affect the application underneath. Instead, when I press Esc to hide the Grid, I end up accidentally closing dialog boxes because the escape key triggers both mouseless and the app below. I really hope this gets a fix.

### Steps to Reproduce

1. Assign Escape to hide the overlay. 
2. Be on an app or dialog that closes its window with Escape.
3. Open/show Mouseless grid.
4. Press escape to hide the grid.
5. The window below will also escape.

**Comment by croian** [comment]
Thank you for this, @ognistik.  Will fix this to make sure it behaves as desired.  In the meantime, if you set the keybinding to “Escape tap” I think it will make things work as you’d like (just 50-100ms slower :)

**Comment by ognistik** [comment]
Thank you so much for this. It may have been my misunderstanding and not a bug after all. I guess that the overlay was closing on the key down event, while the key up event was affecting the application underneath. It makes sense that if I set the overlay to close on the key up event, nothing gets transmitted to the other app. So... maybe no fix needed here, feel free to close this one up.

**Comment by croian** [comment]
i do think it makes sense for keydown-bound actions to not send upstrokes to the underlying app (hard to think of when it would be desirable), so will definitely work to make that the case (or at least the default)!

in fact i thought I had already implemented it this way, so perhaps this is a regression.  i really appreciate that you raised it!

**Comment by croian** [comment]
released in v0.2.2
