### ISSUE TITLE
Non-english layouts are cancelling the input instead of being mapped to default English keyboard

### ISSUE THREAD

**Issue by vlnn** [croian/mouseless-issues#39]
### mouseless version

0.2.1

### macOS version

15.1.1

### What happened?

I have two keyboard layouts switched with fn button. If I'm using non-english layout (e.g. Ukrainian one) the Mouseless is pretty much useless until I switch back to the US one. I expect that pressing `ЙЦ` in Mouseless mode will be same as pressing `QW` as these letters are located on same keys. This will lessen the quantity of mode changes and will make Mouseless much better integrated into multiple languages flows.

### Steps to Reproduce

Add any Cyrillic keyboard layout, switch to it, press LeftCommand, press `QQ` — instead of first cell being chosen, the Mouseless silently exits.

**Comment by croian** [comment]
i think this might be related to #30 -- either way, will investigate and fix 👍

**Comment by croian** [comment]
I realize this issue may have made some users unable to take advantage of their trial period as a chance to actually evaluate the product before buying, and I sincerely apologize for that.

If anyone affected by this issue would like a renewal of their trial license once I get this fix in (aiming for Friday Dec 20), please reach out to me via the [support email](https://mouseless.click/support) and I will gladly renew your trial period.

In retrospect, I should have made the trial period longer during this initial launch, but unfortunately, there are some difficulties in changing that now that things are already in motion.

**Comment by croian** [comment]
making progress on this one (and #30), and I think i'm just about there with the fix.

there will probably be a remaining issue to solve -- `alt` and `ctrl` might not work as `hold_for` actions (e.g. `hold_for_right_click`), nor as modifiers in keybindings in non-`U.S.` layouts.  i think I'll be able to solve this additional issue soon, but not for this release.

**Comment by croian** [comment]
FIXED.  As mentioned, for non-US layouts, alt and ctrl will not work for actions/keybindings that combine with printable chars (should be fine for triggering actions aside from that though) for now.

**Comment by croian** [comment]
note sure if referencing an issue causes a notification, but just in case... @vlnn you might be interested in using the prerelease linked above -- should let you use Ukrainian layout now :)

**Comment by vlnn** [comment]
@croian, thanks, looking into it

**Comment by croian** [comment]
released in v0.2.2

**Comment by korgoth** [comment]
Hm, this doesnt seem to work for me (using 0.3.1) and Bulgarian (Phonetic) input. Is there an option that should be activated or anything else i am missing?

**Comment by croian** [comment]
hi @korgoth, did you use the Bulgarian layout to assign mouse action keys?  currently, you have to be in the same layout as the characters used in `mouse action keys`, but #108 will address this.

if this isn't the issue, if you attach a screenshot of your grid config, perhaps I can help diagnose further

**Comment by korgoth** [comment]
I am constantly switching between Bulgarian and Latin. So it seems a no-go at the moment, at least until #108 comes out. Guess i will just wait for it to happen.

**Comment by croian** [comment]
@korgoth [v0.4.0-preview.0](https://github.com/croian/mouseless/releases/tag/v0.4.0-preview.0) should have the changes you need 👍

**Comment by korgoth** [comment]
A quick test seems to show that things are working as expected! Thank you! I am purchasing a license now :)
