### ISSUE TITLE
Add support for AZERTY layout

### ISSUE THREAD

**Issue by ebjarstal** [croian/mouseless-issues#4]
### Problem Description

I have a French ISO keyboard layout on my MacBook Air M1. When the grid is shown, clicking 'A' twice on my keyboard is treated as clicking on 'Q' twice. 'A' and 'Q' are inverted. Same goes for 'Z' and 'W' as well as 'M' and ','.

### Proposed Solution

I won't pretend to know the technical details to provide a direct solution. I suppose a solution could be to read a key click directly as a character input rather than a key press at a specific location on the keyboard.

**Comment by croian** [comment]
I appreciate this.  I knew I'd probably have to make some changes for international keyboards eventually.  Will look into it and find a solution!

**Comment by justuskilianwolff** [comment]
Same for QWERTZ.

**Comment by dmbfm** [comment]
I use the colemak layout and it also won't work properly.

**Comment by ochicf** [comment]
Doesn't for Dvorak either. It looks like the original QWERTY keys are always used.

Thanks for looking into it!

**Comment by narze** [comment]
I think adding option for software-level keypress would be nice, so it'll support any english keyboard layouts.

**Comment by cheerfulstoic** [comment]
❤️  Excited to try noiseless, but without Dvorak support it’s a no-go for me 😅

One thing you might keep in mind: I use the “Dvorak - QWERTY ⌘“ layout which means that QWERTY keys are used while command is held down.  I notice that mouseless uses the ⌘ key, but maybe never at the same time as another key (??). Probably a UX question there to solve if so

Thanks for looking at this!

**Comment by croian** [comment]
fixed!  the patch release later today should support international and alternate (dvorak, colemak etc) layouts 🤙🤙

**Comment by croian** [comment]
@cheerfulstoic i'll take a look at that layout soon and see how things work with it.  thank you for the heads up!  didn't know it was a thing
