### ISSUE TITLE
Toggle button to toggle overlay

### ISSUE THREAD

**Issue by gcerquant** [croian/mouseless-issues#40]
### Problem Description

Sometimes, I open the overlay by mistake. I wish I had a faster way to close it.
The fastest way is with the finger that opened it.

### Proposed Solution

I would love to be able to toggle the overlay with one key:

<img width="552" alt="image" src="https://github.com/user-attachments/assets/ffca237b-2dd0-491a-8652-e3c220a65539" />

(this currently does not work, not surprisingly, but  I would configure it like that).

### Additional Context

The only time I want to close it is if I opened it by mistake. I feel like it's a double punition to have to think how to close it.

**Comment by vlnn** [comment]
There's toggle option in settings file, but it's buggy and thus hidden. See https://github.com/croian/mouseless-issues/issues/13

**Comment by gcerquant** [comment]
I have seen in https://github.com/croian/mouseless-issues/issues/13 that there is a (temporarily disabled) toggle.

Closing this issue, sorry for the noise.

**Comment by gcerquant** [comment]
well, you were faster ;-)

**Comment by vlnn** [comment]
When I (at last!) checked the expected behavior in 0.3.0-preview3 with setting same key both to `Show overlay` and `Hide overlay` it works as a charm.

**Comment by croian** [comment]
@vlnn thank you for confirming! :)
