### ISSUE TITLE
Does not work with Russian keyboard (and possibly other languages too)

### ISSUE THREAD

**Issue by spixone** [croian/mouseless-issues#43]
### mouseless version

0.2.1

### macOS version

15.0.1

### What happened?

I can't blindly type in English, so I decided to convert the config to Russian, however it doesn't work.
The grid view has changed, but the application does not respond to taps.
Please fix this. For now, unfortunately, the app doesn't make sense to me.

<img width="715" alt="image" src="https://github.com/user-attachments/assets/5f94072c-2f0f-46a8-9175-a2bd768d8acc" />
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/e19f2ce2-dbb0-402e-82bb-c95ff53ea1c8" />

### Steps to Reproduce

Change the config to letters of the Russian alphabet.

**Comment by croian** [comment]
hi @spixone, thank you for the report!  the screenshot is helpful too 🙏  this is probably the same issue as #39, which i'll be working on for the next release.  so i'll close this one to clean things up, and we can continue the conversation there
