### ISSUE TITLE
Text underneath popup grid is sometimes hard to read

### ISSUE THREAD

**Issue by cheuk-cheng** [croian/mouseless-issues#45]
### mouseless version

0.2.1

### macOS version

15.1

### Other system input apps

Hazeover, Hyperkey, Karabiner-Elements, Woosh

### What happened?

The text of some apps is sometimes difficult to read underneath the popup grid from mouseless due to all the vertical and horizontal lines, thus making it hard for the user to choose what keys to press to click a particular screen area.  It will be nice to have a setting to control the opacity/transparency for the popup grid.

### Steps to Reproduce

Install the "Other system input apps" on a macOS machine, run some apps like Visual Studio Code, Google Chrome, etc and and press command key after running mouseless.

**Comment by croian** [comment]
hi @cheuk-cheng, you can control the opacity of the grid, background, and characters independently, as well as a "master opacity" multiplier.  press tab while the overlay is up to bring up the config editor where you can adjust these settings.

please see the [documentation](https://github.com/croian/mouseless-issues/blob/main/mouseless_documentation.md) for more information.

**Comment by croian** [comment]
closing the issue -- please let me know if you have further questions though and we can follow up
