### ISSUE TITLE
Improve grid layout on monitors of differing aspect ratios

### ISSUE THREAD

**Issue by CharlesMagnuson** [croian/mouseless-issues#49]
### Problem Description

When I invoke Mouseless on a MacBook Pro's monitor, the grid displayed contains readable character pairings. When I hit a character pair such as MM, the sub-grid that replaces the MM rectangle displays the QWERTY keyboard layout:
![wide](https://github.com/user-attachments/assets/ab4dcb0a-3546-40b2-9ece-f8e4e7344803)

My external monitors are oriented vertically with a 1800 x 3200 resolution, making them far taller than my MacBook Pro's monitor. When I move the Mouseless grid over to one of the external monitors, the character pairings become unreadable because they are squished together. Much more troubling is that when I hit a character pair such as MM, the sub-grid that appears does not use the QWERTY layout. The top row is QWE, but after that the characters move to new rows so quickly that I cannot accurately place my cursor:
![tall](https://github.com/user-attachments/assets/94baaf94-7b1f-4de6-9674-da75b9c3cd35)
![IMG_2787](https://github.com/user-attachments/assets/41b1ec55-7c12-4ada-8d1e-b80c0d9cc53f)

I've tried decreasing the size of the characters displays so that they are not so squished together on the external monitors, but doing so makes the characters super small and hard to read on the laptop monitor. I'm not sure there's a happy middle ground setting I can use.

### Proposed Solution

It would be nice if the grid stretched itself in a more graceful manner between screens of differing aspect ratios. Automatic character sizing based on the pixel size of each grid might be a good solution. Beyond that, if a monitor becomes taller than it is wide, maybe the sub-grid within a cell only uses the left side of the keyboard so that keys can still appear in a location in the sub-grid that corresponds with the location on the keyboard.

### Additional Context

Wide: https://youtu.be/mQ0wpYTDqXs
Tall: https://youtube.com/shorts/7vE0J1vd118

**Comment by croian** [comment]
thank you for the report @CharlesMagnuson!  and thank you for the videos/screenshots -- always helpful to see the problem visually 🙏

this seems to be the same issue as #6, which i will be working on for the next release.  keeping this one open as well, for visibility of your screenshots and description

**Comment by risalfajar** [comment]
Also happened to mine, 1920x1080 vertical monitor:
![CleanShot 2024-12-17 at 21 07 21](https://github.com/user-attachments/assets/9b791518-14eb-40ee-9e4c-01c9b152fb66)

**Comment by croian** [comment]
thank you for the additional screen shot @risalfajar.

coming back to this and thinking about it more clearly, i see that the solution will be to implement some from of multiple grid configurations.  i had been planning to do this, but it's clearly needed sooner than later 😅 it may not be as fancy or full-featured as it will eventually be, but at the very least there will be an option for two grid_defns that get assigned to monitors based on aspect ratio (e.g. horizontal vs vertical).

starting work on this now.

**Comment by croian** [comment]
@CharlesMagnuson @risalfajar [v0.2.2-preview.1](https://github.com/croian/mouseless-issues/releases/tag/v0.2.2-preview.1) has been uploaded which addresses this issue.  Any feedback/evaluation is definitely appreciated!

**Comment by risalfajar** [comment]
It worked well!

![CleanShot 2024-12-23 at 06 13 14](https://github.com/user-attachments/assets/0ad21743-94ed-45b4-8f3e-9d3403141152)

**Comment by croian** [comment]
thank you for confirming, @risalfajar!

**Comment by croian** [comment]
released in v0.2.2

**Comment by CharlesMagnuson** [comment]
The update is working beautifully! Thank you for the quick addition.

**Comment by croian** [comment]
no problem!  glad to hear it :)
