### ISSUE TITLE
Pricing Model

### ISSUE THREAD

**Issue by Josh-Piper** [croian/mouseless-issues#54]
### Problem Description

Just going to say, I love the application. Saw it posted on Reddit /r/macapps and wanted to just leave some personal notes on the pricing model. Since this type of topic becomes fairly controversial / outspoken when a Mac application is released to the problem

If you do choose to post on r/Macapps, or advertise on YouTube like bettercomputer/, I just thought I'd note some notes about the pricing model to be more appropriate.

### Proposed Solution

Looking at similar applications such as Homerow/Wooshy/Talon Voice in the accessibility space, they offer discounts depending on country of origin (to be more accomodating to lesser affluent countries), have beta/promo codes.

Otherwise, $10 seems on the cheaper side for when/if it does a public release. So thought I'd just note it early, that I personally would be pay $30 for a lifetime of this.

Would prefer for this application to be more expensive, than turn into the inevitable SaaS subscription pricing model 😓

**Comment by croian** [comment]
thank you very much @Josh-Piper.  I really, really appreciate the feedback and context for the pricing model.  and definitely for the heads up on the r/macapps thread, which I will be commenting in.

i've had others advise me as well that $10 is too low for the product, so I will be taking this into consideration, particularly before I start promoting it and/or doing a 1.0 release after current bugs and essential features are worked out.

if I do change the price, I'm happy that the early adopters got a discount, given the invaluable feedback and support I've gotten, and for their patience with some of the early issues.

thank you again!

**Comment by croian** [comment]
hank you very much @Josh-Piper. I really, really appreciate the feedback and context for the pricing model. and definitely for the heads up on the r/macapps thread, which I will be commenting in.

i've had others advise me as well that $10 is under-valuing the product, so I will take this into consideration, particularly if I start promoting it outside my youtube, and/or before doing a 1.0 release after current bugs and essential features are worked out.

if I do change the price, I don't mind at all that the early adopters got a discount, given the invaluable feedback and support I've gotten, and for their patience with some of the early issues.

thank you again!

**Comment by croian** [comment]
thank you very much @Josh-Piper. I really, really appreciate the feedback and context for the pricing model. and definitely for the heads up on the r/macapps thread, which I will be commenting in.

i've had others advise me as well that $10 is under-valuing the product, so I will take this into consideration, particularly if I start promoting it outside my youtube, and/or before doing a 1.0 release after current bugs and essential features are worked out.

if I do change the price, I don't mind at all that the early adopters got a discount, given the invaluable feedback and support I've gotten, and for their patience with some of the early issues.

thank you again!

**Comment by croian** [comment]
also, thank you for the heads up on per-country pricing.  i'll definitely look into so I'm not pricing people out.

**Comment by risalfajar** [comment]
The idea of per-country pricing is very wise.
Just for context, most engineers in my country earn 300-1500 USD a month, which is tiny compared to earnings in western countries.
