### ISSUE TITLE
Alt and Ctrl do not work for clicks, hold_for actions, or shortcuts with printable characters

### ISSUE THREAD

**Issue by FelixLisczyk** [croian/mouseless-issues#57]
### mouseless version

0.2.1

### macOS version

15.2 (24C101)

### Other system input apps

Karabiner Elements

### What happened?

When I use the `AltLeft` key to perform an alt-click, selecting a sub-cell doesn't work. However, if I use the spacebar and click in the middle of a cell, the `AltLeft` key works fine. The `CommandLeft` key functions correctly whether I'm using the spacebar to click or selecting sub-grid letters. The issue appears to occur only when using the `AltLeft` key with sub-grid letter selection.

### Steps to Reproduce

1. Remove any mouseless key bindings for holding down the `AltLeft` and `CommandLeft` modifier keys
2. Activate the mouseless grid using `CommandLeft tap`
3. Type the letters for the desired cell (e.g., "jk")
4. When the sub-grid appears, test the following:
   - Working case 1: Hold `AltLeft` + press Space (successfully performs alt-click in center)
   - Working case 2: Hold `CommandLeft` + press Space (successfully performs command-click in center)
   - Working case 3: Hold `CommandLeft` + press a sub-grid letter (successfully performs command-click at selected position)
   - Bug case: Hold `AltLeft` + press a sub-grid letter (no click is performed)

Mouseless configuration:

```
always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.25
always_show_subgrid: false
app_version: 0.2.0
background_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
classname: AppConfig
font_size_multiplier: 0.5
grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 26
    num_cells_y: 1
  - border_width: 1.0
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 26
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
grid_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 0.5
hide_cursor_on_click: false
hide_location: bottom_left
keymap:
  close dialog: null
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: null
  execute mouse action: Space
  hide overlay: Escape
  hold for drag: CommandRight
  hold for move: ShiftRight
  hold for right button: ShiftLeft
  release hold/drag: Escape
  repeat last mouse action: AltRight
  show overlay: CommandLeft tap
  switch monitor left: Tab
  switch monitor right: null
  toggle overlay: null
mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
move_duration_ms: 100
move_real_cursor_with_virtual: false
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
  - 4
  - 4
subgrid_font_size_multiplier: 1.0
subgrid_mouse_action_keys: 1234QWERASDFZXCV
subgrid_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 0.5
subgrid_text_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 0.75
tap_threshold_ms: 200
text_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 0.75
window_opacity: 1.0
```

**Comment by croian** [comment]
Thank you @FelixLisczyk, will look into this and hopefully find a fix!  Mac is very funky with the alt key, but I've found ways around the funkiness before.

**Comment by croian** [comment]
This is fixed for QWERTY layouts, and I've split off non-QWERTY layouts into #93

**Comment by FelixLisczyk** [comment]
Thank you, @croian. I can confirm that Alt-Clicks are now working correctly in the preview version.

**Comment by croian** [comment]
thank you for confirming, @FelixLisczyk!
