### ISSUE TITLE
Internet connection error dialog when launching the app at login

### ISSUE THREAD

**Issue by FelixLisczyk** [croian/mouseless-issues#59]
### mouseless version

0.2.1

### macOS version

15.2 (24C101)

### Other system input apps

Karabiner Elements

### What happened?

When mouseless launches automatically at login, it checks for an internet connection and shows an error message if the connection hasn't been established yet. This happens even though the app has already been activated with a valid license. I believe the error message is unnecessary and disrupts the user experience, as a licensed app should not need internet access to function normally at startup.

### Steps to Reproduce

1. Activate mouseless with a valid license
2. Enable "Launch at login" for mouseless
3. Turn off Wi-Fi
3. Restart the computer
5. Mouseless launches automatically and shows an error dialog about not being able to connect to the internet

![mouseless-internet-error](https://github.com/user-attachments/assets/b8f86d4c-e126-4791-81f1-e63990a516f5)

**Comment by croian** [comment]
Thank you for the report @FelixLisczyk!  I'm glad you brought this up.  This certainly isn't ideal for a startup app, but I'll have to think about how to go about this until I get offline license validation set up, which I will try to do soon.

In the meantime, maybe just a friendlier, more explanatory alert is the way to go?  Open to suggestions if there are alternatives!

**Comment by FelixLisczyk** [comment]
Thank you for your quick response! The issue with my machine was that the Wi-Fi connection took a few seconds to establish, and mouseless launched before this process was completed. Here's a possible solution:

1. Launch the app without immediately checking the license.
2. Queue the license validation to occur in the background once network connectivity is detected.
3. Only show error messages if the license is actually invalid, not for connection issues.

**Comment by croian** [comment]
no problem!  oh I see, I thought it was only an issue when wi-fi is fully switched off  (instead of just not connected yet).  in this case, I will try to get an alleviation in as soon as i can!

**Comment by jasonjurotich** [comment]
Please, this is very important that it is not trying to connect on startup. Please follow what Felix indicated above because I use a Mac Mini M4 as a portable machine and this gets really bothersome each time I have to plug it in. Thanks!!

**Comment by croian** [comment]
this is fixed, thanks to offline licensing being implemented 👍

**Comment by croian** [comment]
released in v0.2.2
