### ISSUE TITLE
Issue on startup on no network mode

### ISSUE THREAD

**Issue by Srini-B** [croian/mouseless-issues#60]
### mouseless version

0.2.1

### macOS version

15.2

### What happened?

On system startup, app opens before all, even before system can auto connect to Wi-Fi, during this time, app throws an error, check your network connection and try again, clicking OK quits the app, I have to open it again.

### Steps to Reproduce

Turn off the Wi-Fi, boot the system when app is on startup. 
Open the app in offline mode (not tried yet, but must be same)

**Comment by croian** [comment]
Hi @Srini-B, thank you for the report!  This issue is being tracked at #59, so will close this as duplicate.  I appreciate you taking the time to contribute here!
