### ISSUE TITLE
Highlight first letter to press for cell on grid 

### ISSUE THREAD

**Issue by jonasscholten** [croian/mouseless-issues#63]
### Problem Description

When opening the grid it can be overwhelming to see all possible key combinations at once. It takes a bit to find the first letter you need to push for a cell and differentiate it from the second letter.

### Proposed Solution

Highlight the first letter you need to push for a cell in a different color or bold.

**Comment by iminlikewithyou** [comment]
i think lowering the opacity of the second letter may be better - it could probably be in the settings to change the options for the first and second letter, but i do really like this because sometimes i just press the wrong first letter
