### ISSUE TITLE
Disable "Always-on Sub-Grid" by default

### ISSUE THREAD

**Issue by risalfajar** [croian/mouseless-issues#76]
### Problem Description

The always-on sub-grid makes things hard to see:
![CleanShot 2024-12-18 at 13 21 20](https://github.com/user-attachments/assets/ed43c052-a30f-4ff4-9f91-e594005ead0a)

### Proposed Solution

It's better to disable it by default:
![CleanShot 2024-12-18 at 13 21 46](https://github.com/user-attachments/assets/7c62681c-6b90-483b-a0c5-f73e228a8722)

And only show it when a grid has been selected:
![CleanShot 2024-12-18 at 13 22 32](https://github.com/user-attachments/assets/511b00ce-e8ac-4227-b97a-a22f0ae74fff)

**Comment by croian** [comment]
thank you for this suggestion, @risalfajar.  I think this is the right call, particularly for people just coming on board to the program.  this is done in the forthcoming release.

**Comment by croian** [comment]
released in v0.2.2
