### ISSUE TITLE
Overlay doesn't show if show and hide key is the same

### ISSUE THREAD

**Issue by risalfajar** [croian/mouseless-issues#77]
### mouseless version

0.2.1

### macOS version

15.2

### Other system input apps

Only Karabiner, because I use a Windows keyboard

### What happened?

If I set the same key for show and hide overlay, the overlay won't show at all
![CleanShot 2024-12-18 at 13 50 14](https://github.com/user-attachments/assets/050e63e3-3ca1-4883-a931-8406151005e9)

### Steps to Reproduce

1. Open config
2. Change show and hide overlay key to the same key

**Comment by croian** [comment]
fixed in the forthcoming release 👍
