### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by tl87** [croian/mouseless-issues#8]
### Problem Description

This would be awesome on Linux.

### Proposed Solution

Port to Linux maybe 👍🏻

**Comment by croian** [comment]
Roger that!  Hope to be able to get to this sooner than later.

**Comment by FetchFast** [comment]
warpd is very similar my friend

**Comment by croian** [comment]
Thank you all for showing your interest!  I'm happy to say I'm officially entering the exploratory phase of Linux (and Windows) development! 🎉🎉

I've created #68 so users interested in tracking progress have immediate context when linked to the issue, and will thus close this one as a duplicate.

Cheers!

**Comment by croian** [comment]
Btw please ignore how github says closed as either "completed" or "not planned" -- those are the only two options, both of which are very misleadling 🙃
