### ISSUE TITLE
Doesn't work without Internet/Network Access (needs offline license validation)

### ISSUE THREAD

**Issue by ognistik** [croian/mouseless-issues#80]
### mouseless version

v0.2.1

### macOS version

15.2 (24C101)

### Other system input apps

Karabiner Elements

### What happened?

Today, after restarting my system because of some frustrating Internet issues, I realized that Mouseless cannot open/doesn't work (at all) without Internet. I will soon be traveling without access to the Internet 24/7, so for others in a similar situation I think this is actually quite concerning.

![2024-12-18 at 16 57 46@2x](https://github.com/user-attachments/assets/982db732-474e-487f-a253-fe114012b44d)

### Steps to Reproduce

1. Quit Mouseless.
2. Turn off WiFi
3. Activate Mouseless

**Comment by croian** [comment]
hi @ognistik, thank you for making this issue, I understand it's an important one.  i will expedite my efforts to get offline license validation working, doing my best to get it in before people travel for the holidays.

**Comment by croian** [comment]
i'm about to make another preview release, and will then be looking into this one today.  hoping to squeeze it in for monday's release 🤞

**Comment by croian** [comment]
got the core of this working!  just need to fill in workflow details, etc.  will be in the release tomorrow!

**Comment by croian** [comment]
released in v0.2.2
