### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by twiggshub** [croian/mouseless-issues#88]
### Problem Description

The app will not starts when not connected to a network, rendering it unless the app starts in online-mode. Seems to work indefinitely if it launches when there is internet, but it can not launch other than that. 

I will have to be without internet for a few days at the end of the week, no offline mode will kill me! 

### Proposed Solution

Enable offline mode, perhaps not need to query for internet until it can run?

**Comment by ognistik** [comment]
[Here](https://github.com/croian/mouseless-issues/issues/80) <- it's a high priority issue that will hopefully be solved soon
