### ISSUE TITLE
Pressing Hide Overlay key should not pass through to the application

### ISSUE THREAD

**Issue by krschacht** [croian/mouseless-issues#94]
### mouseless version

preview1

### macOS version

Sonoma 14.4.1

### What happened?

I changed my Hide Overlay key to Escape. It works great and it's very intuitive: Command triggers the overlay and if I change my mind I press Escape to quickly hides it.

However, I've noticed that the Escape keypress to hide it also passes through to the program I'm interacting with. Most of the time Esc doesn't cause any harm, but I may have had focus within an input box and esc will unfocus the element.

So... when a key is assigned as the Hide Overlay key, if it's successfully captured and triggers the hide it should "use up" that keypress so that the key doesn't trigger any further actions.

### Steps to Reproduce

I just described that

**Comment by ognistik** [comment]
[Here](https://github.com/croian/mouseless-issues/issues/35) <- The solution is in this thread

**Comment by krschacht** [comment]
Ah, dupe, sorry!
