### ISSUE TITLE
Different overlay layouts

### ISSUE THREAD

**Issue by aboudelh** [croian/mouseless-issues#98]
### Problem Description

The overlay layout starts at AA at the top left and then goes to ZZ at the bottom right, this isn't very intuitive. 

### Proposed Solution

It would be cool if we could modify what the overlay layout is, for example a Qwerty-esque layout similar to the sub-cell selection but extended, and any others. This would allow the user to make a mental map of the screen on the keyboard, and we don't need to check the letters in the overlay as much, just kinda intuitively select the cells we want.
The feature would need to be validated; I don't know how well it would actually work in practice, and keyboard shapes don't necessarily match screen shapes, but its worth including eventually I think.

**Comment by aboudelh** [comment]
ok sorry I just realised this is already possible, closing

**Comment by croian** [comment]
no problem aboudelh.  I'm guessing you found this discussion: #1 

i'll try to get this in the gui soon!

**Comment by aboudelh** [comment]
Yup, I’m tinkering with it right now.
And thank you!
