### ISSUE TITLE
Can't see Grid Overlay

### ISSUE THREAD

**Issue by ayushxshukla** [croian/mouseless-issues#99]
### mouseless version

v0.2.1

### macOS version

Ventura 13.2.1 

### What happened?

I expected that when I click CommandLeft, it'll display an overlay and then based on what key I push it'll click the cursor there. 

The click is working, however there is no overlay. 

https://github.com/user-attachments/assets/61bffcb9-95cc-479f-be41-9f103b651b5a

### Steps to Reproduce

Just installed and tried, nothing special here.

**Comment by croian** [comment]
Hi @ayushxshukla, thank you for the report.  Unfortunately, I don't believe it's working on macos 13 or below.  I apologize for the inconvenience.  I will track progress on it in #71

I'll be happy to renew trial periods for you or anyone who has started one and couldn't use the app, once I have it working for macOS 13.

I am updating the app tonight to not open on macOS 13, to prevent more people from starting trials with it, and I will update the site as well.

I hope to get a VM or hosted solution running soon so I can fix the compatibility issues.

Going to close this issue in favor of #71, but please let me know if you have any more questions!
